### ISSUE TITLE
factor_history: better as dictionary ?

### ISSUE THREAD

**Issue by marcocamma** [suqingdong/impact_factor#1]
Thanks a lot for the very handy module !
I noticed that factor_history is a string.

It would be a lot more convenient if converted as dictionary, something along these lines

```python
        history = dict()
        for _ in impact_factor['factor_history'].split(","):
            _year,_if = _.split(":")
            _year = _year.strip().strip('"')
            _if = _if.strip().strip('"')
            history[int(_year)] = float(_if)
```

What do you think ? Would this break anything internally ?
I could make a PR if you prefer

cheers,
marco

**Comment by suqingdong** [comment]
> Thanks a lot for the very handy module !
> I noticed that factor_history is a string.
> 
> It would be a lot more convenient if converted as dictionary, something along these lines
> 
> ```python
>         history = dict()
>         for _ in impact_factor['factor_history'].split(","):
>             _year,_if = _.split(":")
>             _year = _year.strip().strip('"')
>             _if = _if.strip().strip('"')
>             history[int(_year)] = float(_if)
> ```
> 
> What do you think ? Would this break anything internally ?
> I could make a PR if you prefer
> 
> cheers,
> marco

Hey, @marcocamma :

factor_history is a json string generated by `json.dumps`, if you want to use it, just use `json.loads` like follow:
```python
>>> import json
>>> from impact_factor import ImpactFactor
>>> IF = ImpactFactor()
>>> res = IF.search('nature')
>>> res['factor_history']
'{"2015": "38.138", "2017": "41.577", "2016": "40.137", "2019": "42.778", "2018": "43.07"}'
>>> json.loads(res['factor_history'])['2018']
'43.07'
```
or I can add a line at function `ImpactFactor.search`:
```python
context['factor_history'] = json.loads(context['factor_history'])
```

**Comment by marcocamma** [comment]
Indeed using json.loads is easier but it still leaves the years (and the impact factors) as strings instead of integers and floats respectively.
I can work with the module as is so if it is too much of an headache don't worry, else I would change it to

```python
temp = json.loads(context['factor_history'])
context['factory_history'] = dict()
for year,impact_factor in temp.items():
    if impact_factor != "":
        context['factory_history'][int(year)] = float(impact_factor)
```

**Comment by suqingdong** [comment]
> I can work with the module as is so if it is too much of an headache don't worry

If you need year as int and factor as float, dictionary comprehension is more 'Pythonic':
```python
factor_history = json.loads(context['factor_history'])
context['factor_history'] = {int(k): float(v) for k, v in factor_history.items() if v}
```
