### ISSUE TITLE
error importing module

### ISSUE THREAD

**Issue by pnguyen-biotech** [suqingdong/impact_factor#2]
I encountered this error when I try to import the impact_factor module in python. Hope you can take a look. Thanks!
![image](https://user-images.githubusercontent.com/80936944/151230024-4a495a8f-83c7-41ad-aa73-7281e2e83332.png)

**Comment by suqingdong** [comment]
> I encountered this error when I try to import the impact_factor module in python. Hope you can take a look. Thanks! ![image](https://user-images.githubusercontent.com/80936944/151230024-4a495a8f-83c7-41ad-aa73-7281e2e83332.png)

`pip install webrequests`
