### ISSUE TITLE
Update of base spreadsheet

### ISSUE THREAD

**Issue by jannisborn** [suqingdong/impact_factor#3]
Hi there, great package! 
I'm planning to include a wrapper into the [paperscraper](https://github.com/PhosphorylatedRabbits/paperscraper) package and I'm wondering whether / how the base spreadsheet will be updated.  Currently it seems to list 2021 impact factors.

I now I can run `impact_factor build` but it does not update the spreadsheet.

Thanks for a response!

**Comment by utf** [comment]
Hi @jannisborn, I believe you can update the database using: 

```bash
impact_factor build -k YOUR_NCBI_API_KEY --force --update
```

Obtaining an NCBI API key is trivial, [see here](https://support.nlm.nih.gov/knowledgebase/article/KA-05317/en-us).

However, I've just started this running and it looks like it will take a long time.

**Comment by yiouyou** [comment]
+1

Thanks

**Comment by utf** [comment]
Hi @suqingdong, do you have a script you used to compile the initial list of impact factors? I'd be happy to re-run it if you're able to share it.

**Comment by jannisborn** [comment]
I'd also be interested in that!

@utf I wrote a wrapper class for `paperscraper` [here](https://github.com/jannisborn/paperscraper/blob/main/paperscraper/impact.py#L12), it also has some fuzzy search logic to search entries more robustly. But the data behind it is still the outdated one from 2021 :/

**Comment by utf** [comment]
Just FYI, I have found this list here which seems to be up-to-date as of 2024 https://www.researchgate.net/publication/381580823_Journal_Citation_Reports_JCR_Impact_Factor_2024_PDF_Web_of_Science

I think it should be possible to re-build the database from this.

**Comment by utf** [comment]
One final update. This script will take the file above and reformat it properly for `impact_factor`.
```python
import pandas as pd
import re

def get_factor(factor):
    try:
        return float(factor)
    except:
        return 0
    
def update_category(category):
    res = re.findall(r'\|(Q\d)\|', category)
    try:
        return f"({res[0]})"
    except:
        return pd.NA

df_new = pd.read_excel("CopyofImpactFactor2024.xlsx")

# some impact factors are not floats so parse them in advance
df_new.JIF = [get_factor(factor) for factor in df_new.JIF]

# the category format has changed and some are missing
df_new.Category = [update_category(category) for category in df_new.Category]
df_new = df_new[~pd.isna(df_new.Category)]

# reformat columns to be consistent with before
df_new.rename({"Name": "Journal Name", "EISSN": "eISSN", "JIF": "2021 JIF"}, axis=1, inplace=True)
df_new.drop(columns=["Abbr Name", "JIF5Years"], inplace=True)

# save the new list
df_new.to_excel("2024_JCR_IF.xlsx", index=False)
```

The database can then be rebuilt using:
```
impact_factor build --excel 2024_JCR_IF.xlsx --update --force
```

**Comment by jannisborn** [comment]
Great effort @utf ! Just tried this but after a few dozen journals were updated, I got an error:

```py
  File "/Users/jab/miniconda3/envs/paperscraper/lib/python3.10/site-packages/impact_factor/bin/_build.py", line 58, in main
    res = NlmCatalog.search(f'{issn}[ISSN]')
  File "/Users/jab/miniconda3/envs/paperscraper/lib/python3.10/site-packages/impact_factor/core/nlmcatalog.py", line 35, in search
    if (count := result['count']) != '1':
KeyError: 'count'
```

seems like the result object was empty, reason was that some journal had an empty eISSN (Lancet Respiratory Medicine)

Did you encounter the same?

**Comment by utf** [comment]
An easy fix would be to filter out the entries without either an eISSN or ISSN and then try building again. I ended up just using the entries I needed for my purpose.

**Comment by suqingdong** [comment]
> An easy fix would be to filter out the entries without either an eISSN or ISSN and then try building again. I ended up just using the entries I needed for my purpose.

Thank you for providing the document. I have updated the database, filtering out data with IF<0.1 and N/A. The latest PyPI version is 1.1.1.

```bash
python3 -m pip install -U impact-factor
```

**Comment by jannisborn** [comment]
Thanks a lot @suqingdong that is super useful!!
